#!/bin/bash
blockMesh
checkMesh
cp -r A/* 0/ 
#setFields
rm -r SummaryData.dat
rm -rf postProcessing
rm -rf dynamicCode
decomposePar -force
funkySetFields
mpirun -np 4 interThermalPhaseChangeFoam_SGS -parallel
