#!/bin/bash -l
#PBS -N Cond-Re_0800
#PBS -l mppwidth=24
#PBS -l walltime=48:00:00
#PBS -q regular
#PBS -e job-$PBS_JOBID.err
#PBS -o job-$PBS_JOBID.out
#PBS -m abe
#PBS -A m1631

#Shared memory stuff
module unload xt-shmem
export CRAY_ROOTFS=DSL

#Set some consts
N_PROCS=24
PROB_DIR=ASRPhaser_CondInflow_Re_0800
SOLVER=ASRInterThermalPhaseFoam

#Load in the OpenFOAM stuff
module use $HOME/modules
module load OpenFOAM/2.1.1
source $HOME/OpenFOAM/OpenFOAM-2.1.1/etc/bashrc

#Set up the job
cd $HOME
echo "Moving CFD file to scratch space"
cp -r CFD_Studies/$PROB_DIR $SCRATCH
cd $SCRATCH/$PROB_DIR

#Initialization
m4 constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict
blockMesh
cp -r A/* 0/ 
funkySetFields -time 0 -allowFunctionObjects
decomposePar -force

#Initial run
aprun -n $N_PROCS $SOLVER -parallel > log.txt

